spring:
  application:
    name: NexPay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexpayDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:naman1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  master-key: dkbrlgh3jna8903fesnfbiou3nnfehafjkeb3iuohjkfbiw946eu