spring:
  application:
    name: NexPay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/nexpayDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:naman1234}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect